/*
Copyright 2018 Nexinto

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	icinga_nexinto_com_v1 "github.com/Soluto-Private/kubernetes-icinga/pkg/apis/icinga.nexinto.com/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeChecks implements CheckInterface
type FakeChecks struct {
	Fake *FakeIcingaV1
	ns   string
}

var checksResource = schema.GroupVersionResource{Group: "icinga.nexinto.com", Version: "v1", Resource: "checks"}

var checksKind = schema.GroupVersionKind{Group: "icinga.nexinto.com", Version: "v1", Kind: "Check"}

// Get takes name of the check, and returns the corresponding check object, and an error if there is any.
func (c *FakeChecks) Get(name string, options v1.GetOptions) (result *icinga_nexinto_com_v1.Check, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(checksResource, c.ns, name), &icinga_nexinto_com_v1.Check{})

	if obj == nil {
		return nil, err
	}
	return obj.(*icinga_nexinto_com_v1.Check), err
}

// List takes label and field selectors, and returns the list of Checks that match those selectors.
func (c *FakeChecks) List(opts v1.ListOptions) (result *icinga_nexinto_com_v1.CheckList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(checksResource, checksKind, c.ns, opts), &icinga_nexinto_com_v1.CheckList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &icinga_nexinto_com_v1.CheckList{}
	for _, item := range obj.(*icinga_nexinto_com_v1.CheckList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested checks.
func (c *FakeChecks) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(checksResource, c.ns, opts))

}

// Create takes the representation of a check and creates it.  Returns the server's representation of the check, and an error, if there is any.
func (c *FakeChecks) Create(check *icinga_nexinto_com_v1.Check) (result *icinga_nexinto_com_v1.Check, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(checksResource, c.ns, check), &icinga_nexinto_com_v1.Check{})

	if obj == nil {
		return nil, err
	}
	return obj.(*icinga_nexinto_com_v1.Check), err
}

// Update takes the representation of a check and updates it. Returns the server's representation of the check, and an error, if there is any.
func (c *FakeChecks) Update(check *icinga_nexinto_com_v1.Check) (result *icinga_nexinto_com_v1.Check, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(checksResource, c.ns, check), &icinga_nexinto_com_v1.Check{})

	if obj == nil {
		return nil, err
	}
	return obj.(*icinga_nexinto_com_v1.Check), err
}

// Delete takes name of the check and deletes it. Returns an error if one occurs.
func (c *FakeChecks) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(checksResource, c.ns, name), &icinga_nexinto_com_v1.Check{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeChecks) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(checksResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &icinga_nexinto_com_v1.CheckList{})
	return err
}

// Patch applies the patch and returns the patched check.
func (c *FakeChecks) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *icinga_nexinto_com_v1.Check, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(checksResource, c.ns, name, data, subresources...), &icinga_nexinto_com_v1.Check{})

	if obj == nil {
		return nil, err
	}
	return obj.(*icinga_nexinto_com_v1.Check), err
}
