/*
Copyright 2018 Nexinto

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	icinga_nexinto_com_v1 "github.com/Nexinto/kubernetes-icinga/pkg/apis/icinga.nexinto.com/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHostGroups implements HostGroupInterface
type FakeHostGroups struct {
	Fake *FakeIcingaV1
	ns   string
}

var hostgroupsResource = schema.GroupVersionResource{Group: "icinga.nexinto.com", Version: "v1", Resource: "hostgroups"}

var hostgroupsKind = schema.GroupVersionKind{Group: "icinga.nexinto.com", Version: "v1", Kind: "HostGroup"}

// Get takes name of the hostGroup, and returns the corresponding hostGroup object, and an error if there is any.
func (c *FakeHostGroups) Get(name string, options v1.GetOptions) (result *icinga_nexinto_com_v1.HostGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(hostgroupsResource, c.ns, name), &icinga_nexinto_com_v1.HostGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*icinga_nexinto_com_v1.HostGroup), err
}

// List takes label and field selectors, and returns the list of HostGroups that match those selectors.
func (c *FakeHostGroups) List(opts v1.ListOptions) (result *icinga_nexinto_com_v1.HostGroupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(hostgroupsResource, hostgroupsKind, c.ns, opts), &icinga_nexinto_com_v1.HostGroupList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &icinga_nexinto_com_v1.HostGroupList{}
	for _, item := range obj.(*icinga_nexinto_com_v1.HostGroupList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested hostGroups.
func (c *FakeHostGroups) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(hostgroupsResource, c.ns, opts))

}

// Create takes the representation of a hostGroup and creates it.  Returns the server's representation of the hostGroup, and an error, if there is any.
func (c *FakeHostGroups) Create(hostGroup *icinga_nexinto_com_v1.HostGroup) (result *icinga_nexinto_com_v1.HostGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(hostgroupsResource, c.ns, hostGroup), &icinga_nexinto_com_v1.HostGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*icinga_nexinto_com_v1.HostGroup), err
}

// Update takes the representation of a hostGroup and updates it. Returns the server's representation of the hostGroup, and an error, if there is any.
func (c *FakeHostGroups) Update(hostGroup *icinga_nexinto_com_v1.HostGroup) (result *icinga_nexinto_com_v1.HostGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(hostgroupsResource, c.ns, hostGroup), &icinga_nexinto_com_v1.HostGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*icinga_nexinto_com_v1.HostGroup), err
}

// Delete takes name of the hostGroup and deletes it. Returns an error if one occurs.
func (c *FakeHostGroups) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(hostgroupsResource, c.ns, name), &icinga_nexinto_com_v1.HostGroup{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHostGroups) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(hostgroupsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &icinga_nexinto_com_v1.HostGroupList{})
	return err
}

// Patch applies the patch and returns the patched hostGroup.
func (c *FakeHostGroups) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *icinga_nexinto_com_v1.HostGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(hostgroupsResource, c.ns, name, data, subresources...), &icinga_nexinto_com_v1.HostGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*icinga_nexinto_com_v1.HostGroup), err
}
