/*
Copyright 2018 Nexinto

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

// CheckListerExpansion allows custom methods to be added to
// CheckLister.
type CheckListerExpansion interface{}

// CheckNamespaceListerExpansion allows custom methods to be added to
// CheckNamespaceLister.
type CheckNamespaceListerExpansion interface{}

// HostListerExpansion allows custom methods to be added to
// HostLister.
type HostListerExpansion interface{}

// HostNamespaceListerExpansion allows custom methods to be added to
// HostNamespaceLister.
type HostNamespaceListerExpansion interface{}

// HostGroupListerExpansion allows custom methods to be added to
// HostGroupLister.
type HostGroupListerExpansion interface{}

// HostGroupNamespaceListerExpansion allows custom methods to be added to
// HostGroupNamespaceLister.
type HostGroupNamespaceListerExpansion interface{}
